In [4]:
import numpy as np

In [5]:
a = np.array((1.5,2,3))
b = np.array([[1.5,2,3], (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3,3), (4,5,6,1)], [(3,2,1,0), (4,5,6,-1)]])
print(a.shape, b.shape, c.shape)

(3,) (2, 3) (2, 2, 4)


In [6]:
a

array([1.5, 2. , 3. ])

In [7]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c

array([[[ 1.5,  2. ,  3. ,  3. ],
        [ 4. ,  5. ,  6. ,  1. ]],

       [[ 3. ,  2. ,  1. ,  0. ],
        [ 4. ,  5. ,  6. , -1. ]]])

In [10]:
np.zeros((3,4))                #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
d = np.arange(10,25,5)        # Create an array of evenly spaced values (step value)  

In [15]:
d

array([10, 15, 20])

In [16]:
np.linspace(0,2,9)            # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
e = np.full((2,2),7)           #Create a constant array    
f = np.eye(2)                  #Create a 2X2 identity matrix

In [18]:
e

array([[7, 7],
       [7, 7]])

In [19]:
f

array([[1., 0.],
       [0., 1.]])

In [20]:
np.random.random((2,2))        #Create an array with random values

array([[0.80037736, 0.35748682],
       [0.31587542, 0.85304211]])

In [30]:
emp = np.empty((4,2))              #Create an empty array

In [31]:
emp

array([[0.25, 0.5 ],
       [0.75, 1.  ],
       [1.25, 1.5 ],
       [1.75, 2.  ]])

In [32]:
np.save('my_array', a)

In [51]:
np.savez('array.npz', a=a, b=b)

In [34]:
a_loaded = np.load('my_array.npy')

In [35]:
a

array([1.5, 2. , 3. ])

In [36]:
a_loaded

array([1.5, 2. , 3. ])

In [52]:
data = np.load('array.npz')

In [53]:
data['a']

array([1.5, 2. , 3. ])

In [54]:
data['b']

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [77]:
from io import StringIO   # StringIO behaves like a file object
c_io = StringIO(u"0 1\n2 3")

In [78]:
print(c_io.getvalue())

0 1
2 3


In [79]:
np.loadtxt(c_io)

array([[0., 1.],
       [2., 3.]])

In [80]:
d_io = StringIO(u"M 21 72\nF 35 58")

In [81]:
print(d_io.getvalue())

M 21 72
F 35 58


In [83]:
np.loadtxt(d_io, dtype={'names': ('gender', 'age', 'weight'),
                     'formats': ('S1', 'i4', 'f4')})

array([(b'M', 21, 72.), (b'F', 35, 58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [89]:
c_io = StringIO(u"1,0,2\n3,0,4")

In [90]:
print(c_io.getvalue())

1,0,2
3,0,4


In [91]:
x_io, y_io = np.loadtxt(c_io, delimiter=',', usecols=(0, 2), unpack=True)

In [92]:
x_io

array([1., 3.])

In [93]:
y_io

array([2., 4.])

In [105]:
d_io = StringIO(u"1,0,2\n3,0,4")

In [106]:
d_o = np.genfromtxt(d_io, delimiter=',')

In [107]:
d_o

array([[1., 0., 2.],
       [3., 0., 4.]])

In [108]:
np.savetxt("saved.txt", d_o, delimiter=" ")

In [109]:
np.int64          #Signed 64-bit integer types

numpy.int64

In [112]:
np.float32        #Standard double-precision floating point

numpy.float32

In [113]:
np.complex        #Complex numbers represented by 128 floats

complex

In [114]:
np.bool           #Boolean type storing TRUE and FALSE values

bool

In [115]:
np.object         #Python object type

object

In [116]:
np.string_        #Fixed-length string type

numpy.bytes_

In [111]:
np.unicode_       #Fixed-length unicode type

numpy.str_